### ISSUE TITLE
Reminder E-mails for Speakers

### ISSUE THREAD

**Issue by NickSmithTech** [davidfcarr/rsvpmaker-for-toastmasters#14]
We've found in our club that speakers cancel a day or two before the meeting because they haven't prepared.

A solution could be an automated email to speakers much sooner, perhaps 2 or 3 weeks out, with some sort of validation mechanism (click here to confirm you are still speaking) would help with this.

**Comment by davidfcarr** [comment]
There is already an option to send members a reminder of the role they signed up for. You can set up to two reminders, Could be more flexible in terms of allowing you to set them to any period of hours, days, or weeks in advance (right now, just a short list of options).
