### ISSUE TITLE
Associate evaluators to speakers

### ISSUE THREAD

**Issue by NickSmithTech** [davidfcarr/rsvpmaker-for-toastmasters#2]
so when printing, they can be printed together
(John Doe evaluates Jane Doe)

**Comment by davidfcarr** [comment]
So should the software default to saying first evaluator on the list is associated with the first speaker, second evaluator to second speaker and so on? In my home club, the general evaluator sometimes rearranges the order on meeting day according to the preference of the speaker or the experience of the evaluator. 

Even if such arrangements were made in advance, I don't currently have an easy way of reordering speakers and evaluators on the agenda. I can imagine a slick drag-and-drop capability for that might be nice, but it's not something I have working.

The question is how to avoid hard-coding too many assumptions about how a club works into the software, while still supporting a few common patterns.

**Comment by davidfcarr** [comment]
I did think of having an optional table of speakers and evaluators that could appear somewhere on the agenda.

**Comment by NickSmithTech** [comment]
Those are good considerations. In our club, we try to put evaluators in touch with speakers ahead of time, so they're generally static by the time we are printing an agenda. But, an option to disable this would be important (as would any custom option I am looking into adding).

My thought was indeed to offer an option to associate _Evaluator_1 to _Speaker_1, _Evaluator_2 to _Speaker_2.

Re-ordering would be better scoped under a separate issue (which I will make).

For issues that I will add here, if it is just named without a lot of details, it is me putting thoughts in here so I don't forget them. I will either work on them later and send a pull request, add discussion in the comments or close them if I abandon the idea. In this case, I just haven't put a lot of thought into it yet.

**Comment by davidfcarr** [comment]
Here is how I'm handling the reordering issue and associating evaluators with speakers

[https://www.youtube.com/watch?v=6X12LWN3yJU](https://www.youtube.com/watch?v=6X12LWN3yJU)

You include "Evaluates {Speakers}" in the agenda note field for the Evaluator role to turn on the display of the associated speakers.

**Comment by NickSmithTech** [comment]
Nice.
