### ISSUE TITLE
Reorder speakers (and other numbered roles, like Evaluators, etc.)

### ISSUE THREAD

**Issue by NickSmithTech** [davidfcarr/rsvpmaker-for-toastmasters#3]

**Comment by davidfcarr** [comment]
I have some ideas about how to make this work using JQuery UI's Sortable
https://jqueryui.com/sortable/

Open to better ideas

**Comment by NickSmithTech** [comment]
I agree jquery is definetely the way to handle this.

**Comment by NickSmithTech** [comment]
I agree jquery is definetely the way to handle this.
